// Mir — 데이터플레인 ⇄ 제어부 공용 스키마.
//
// 이 파일 하나가 **두 hop 을 모두 정의**한다.
//
//   ③ C 데이터플레인 ⇄ Go 사이드카   : unix socket + length-prefix framing
//   ④ Go 사이드카   ⇄ Go 제어부      : gRPC (service DataPlane)
//
// 사이드카는 대부분의 필드를 그대로 통과시키는 릴레이라, 스키마를 하나로
// 유지하면 두 hop 이 갈라질 여지가 없다.
//
// ── hop ③ 와이어 포맷 (C 의 ipc_server.c 와 반드시 일치) ──────────────
//
//   +--------+--------+------------------+
//   | u32 be | u16 be |     payload      |
//   | length |  type  |    (protobuf)    |
//   +--------+--------+------------------+
//
//   length = sizeof(type) + sizeof(payload)   — 자기 자신은 제외
//   type   = MsgType 값
//
// gRPC 를 C 에 직접 넣지 않은 이유는 성능이 아니라 **스레드 격리**다.
// C 프로세스에 gRPC 스레드 풀이 생기면 컨테이너 cpuset(= worker 코어 포함)을
// 떠돌며 busy-poll 루프를 선점할 수 있다. 사이드카는 별도 컨테이너라
// 애초에 worker 코어에 올라갈 물리적 경로가 없다.
//
// ── 코드 생성 ─────────────────────────────────────────────────────────
//
//   Go : buf generate            (저장소 루트에서. 생성물은 커밋한다)
//   C  : protoc-c --proto_path=proto --c_out=<builddir> proto/dataplane.proto
//        (meson custom_target 이 빌드 중에 실행 — 이미지 빌드 시점에만 필요)
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: dataplane.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ─────────────────────────────────────────────────────────────
// hop ③ 프레임 타입 태그.
//
// enum 값 자체는 payload 에 실리지 않고 프레임 헤더의 u16 에 들어간다.
// 100 미만 = 제어부 → 데이터플레인, 100 이상 = 데이터플레인 → 제어부.
// ─────────────────────────────────────────────────────────────
type MsgType int32

const (
	MsgType_MSG_TYPE_UNSPECIFIED MsgType = 0
	// 제어부 → 데이터플레인
	MsgType_MSG_TYPE_HELLO_REQUEST  MsgType = 1
	MsgType_MSG_TYPE_START_SCENARIO MsgType = 2
	MsgType_MSG_TYPE_STOP_SCENARIO  MsgType = 3
	// 데이터플레인 → 제어부
	MsgType_MSG_TYPE_HELLO_RESPONSE MsgType = 101
	MsgType_MSG_TYPE_TELEMETRY      MsgType = 102
	MsgType_MSG_TYPE_EVENT          MsgType = 103
	MsgType_MSG_TYPE_ACK            MsgType = 104
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0:   "MSG_TYPE_UNSPECIFIED",
		1:   "MSG_TYPE_HELLO_REQUEST",
		2:   "MSG_TYPE_START_SCENARIO",
		3:   "MSG_TYPE_STOP_SCENARIO",
		101: "MSG_TYPE_HELLO_RESPONSE",
		102: "MSG_TYPE_TELEMETRY",
		103: "MSG_TYPE_EVENT",
		104: "MSG_TYPE_ACK",
	}
	MsgType_value = map[string]int32{
		"MSG_TYPE_UNSPECIFIED":    0,
		"MSG_TYPE_HELLO_REQUEST":  1,
		"MSG_TYPE_START_SCENARIO": 2,
		"MSG_TYPE_STOP_SCENARIO":  3,
		"MSG_TYPE_HELLO_RESPONSE": 101,
		"MSG_TYPE_TELEMETRY":      102,
		"MSG_TYPE_EVENT":          103,
		"MSG_TYPE_ACK":            104,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_dataplane_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_dataplane_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{0}
}

type Event_Kind int32

const (
	Event_KIND_UNSPECIFIED     Event_Kind = 0
	Event_KIND_SYNACK_TIMEOUT  Event_Kind = 1 // SYN 보냈으나 SYN-ACK 없음
	Event_KIND_RST_RECEIVED    Event_Kind = 2 // 포트 닫힘 추정
	Event_KIND_UNEXPECTED_FLAG Event_Kind = 3
	Event_KIND_RETRANSMIT      Event_Kind = 4
)

// Enum value maps for Event_Kind.
var (
	Event_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_SYNACK_TIMEOUT",
		2: "KIND_RST_RECEIVED",
		3: "KIND_UNEXPECTED_FLAG",
		4: "KIND_RETRANSMIT",
	}
	Event_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED":     0,
		"KIND_SYNACK_TIMEOUT":  1,
		"KIND_RST_RECEIVED":    2,
		"KIND_UNEXPECTED_FLAG": 3,
		"KIND_RETRANSMIT":      4,
	}
)

func (x Event_Kind) Enum() *Event_Kind {
	p := new(Event_Kind)
	*p = x
	return p
}

func (x Event_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_dataplane_proto_enumTypes[1].Descriptor()
}

func (Event_Kind) Type() protoreflect.EnumType {
	return &file_dataplane_proto_enumTypes[1]
}

func (x Event_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event_Kind.Descriptor instead.
func (Event_Kind) EnumDescriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{8, 0}
}

// ─────────────────────────────────────────────────────────────
// 핸드셰이크 — 제어부가 붙자마자 능력을 조회한다.
// ─────────────────────────────────────────────────────────────
type HelloRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ControlVersion string                 `protobuf:"bytes,1,opt,name=control_version,json=controlVersion,proto3" json:"control_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_dataplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetControlVersion() string {
	if x != nil {
		return x.ControlVersion
	}
	return ""
}

type PortInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PortId        uint32                 `protobuf:"varint,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	Driver        string                 `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty"` // "net_i40e", "net_ice", "net_ena" ...
	Mac           string                 `protobuf:"bytes,3,opt,name=mac,proto3" json:"mac,omitempty"`
	NumaNode      int32                  `protobuf:"varint,4,opt,name=numa_node,json=numaNode,proto3" json:"numa_node,omitempty"`
	DeviceSpec    string                 `protobuf:"bytes,5,opt,name=device_spec,json=deviceSpec,proto3" json:"device_spec,omitempty"` // PCI BDF 또는 MAC (환경에 따라 다름 — eal_args.h 참조)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortInfo) Reset() {
	*x = PortInfo{}
	mi := &file_dataplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortInfo) ProtoMessage() {}

func (x *PortInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortInfo.ProtoReflect.Descriptor instead.
func (*PortInfo) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{1}
}

func (x *PortInfo) GetPortId() uint32 {
	if x != nil {
		return x.PortId
	}
	return 0
}

func (x *PortInfo) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *PortInfo) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *PortInfo) GetNumaNode() int32 {
	if x != nil {
		return x.NumaNode
	}
	return 0
}

func (x *PortInfo) GetDeviceSpec() string {
	if x != nil {
		return x.DeviceSpec
	}
	return ""
}

type HelloResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DataplaneVersion string                 `protobuf:"bytes,1,opt,name=dataplane_version,json=dataplaneVersion,proto3" json:"dataplane_version,omitempty"`
	NodeId           string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // 파드명 (HOSTNAME)
	Ports            []*PortInfo            `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty"`
	Lcores           []uint32               `protobuf:"varint,4,rep,packed,name=lcores,proto3" json:"lcores,omitempty"` // 실제로 할당받은 CPU 목록 (cpuset 에서 읽은 값)
	MainLcore        uint32                 `protobuf:"varint,5,opt,name=main_lcore,json=mainLcore,proto3" json:"main_lcore,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_dataplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{2}
}

func (x *HelloResponse) GetDataplaneVersion() string {
	if x != nil {
		return x.DataplaneVersion
	}
	return ""
}

func (x *HelloResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HelloResponse) GetPorts() []*PortInfo {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *HelloResponse) GetLcores() []uint32 {
	if x != nil {
		return x.Lcores
	}
	return nil
}

func (x *HelloResponse) GetMainLcore() uint32 {
	if x != nil {
		return x.MainLcore
	}
	return 0
}

// ─────────────────────────────────────────────────────────────
// 명령
// ─────────────────────────────────────────────────────────────
type StartScenarioRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	// 리플레이 대상 PCAP. **파일 내용이 아니라 경로만** 전달한다.
	// GB 단위일 수 있으므로 제어 채널로 실어 보내지 않고 공유 볼륨을 경유한다.
	// 제어부가 RW 로, 데이터플레인이 RO 로 같은 PV 를 마운트한다.
	PcapPath      string `protobuf:"bytes,2,opt,name=pcap_path,json=pcapPath,proto3" json:"pcap_path,omitempty"`
	RatePps       uint64 `protobuf:"varint,3,opt,name=rate_pps,json=ratePps,proto3" json:"rate_pps,omitempty"`       // 0 = 최대 속도
	DurationS     uint32 `protobuf:"varint,4,opt,name=duration_s,json=durationS,proto3" json:"duration_s,omitempty"` // 0 = 무한
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartScenarioRequest) Reset() {
	*x = StartScenarioRequest{}
	mi := &file_dataplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartScenarioRequest) ProtoMessage() {}

func (x *StartScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartScenarioRequest.ProtoReflect.Descriptor instead.
func (*StartScenarioRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{3}
}

func (x *StartScenarioRequest) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *StartScenarioRequest) GetPcapPath() string {
	if x != nil {
		return x.PcapPath
	}
	return ""
}

func (x *StartScenarioRequest) GetRatePps() uint64 {
	if x != nil {
		return x.RatePps
	}
	return 0
}

func (x *StartScenarioRequest) GetDurationS() uint32 {
	if x != nil {
		return x.DurationS
	}
	return 0
}

type StopScenarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId    string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopScenarioRequest) Reset() {
	*x = StopScenarioRequest{}
	mi := &file_dataplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopScenarioRequest) ProtoMessage() {}

func (x *StopScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopScenarioRequest.ProtoReflect.Descriptor instead.
func (*StopScenarioRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{4}
}

func (x *StopScenarioRequest) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_dataplane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{5}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ─────────────────────────────────────────────────────────────
// 텔레메트리 — 100ms 주기 push.
//
// 개별 패킷(mbuf)은 절대 이 채널을 넘지 않는다. 148 Mpps 를 프로세스 경계
// 밖으로 내보내는 건 성립하지 않는다. worker lcore 가 per-lcore 카운터에
// 누적한 것을 제어 스레드가 합산해 스냅샷으로만 올린다.
// ─────────────────────────────────────────────────────────────
type PortStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PortId        uint32                 `protobuf:"varint,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	TxPkts        uint64                 `protobuf:"varint,2,opt,name=tx_pkts,json=txPkts,proto3" json:"tx_pkts,omitempty"`
	TxBytes       uint64                 `protobuf:"varint,3,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	TxDrop        uint64                 `protobuf:"varint,4,opt,name=tx_drop,json=txDrop,proto3" json:"tx_drop,omitempty"`
	TxErr         uint64                 `protobuf:"varint,5,opt,name=tx_err,json=txErr,proto3" json:"tx_err,omitempty"`
	RxPkts        uint64                 `protobuf:"varint,6,opt,name=rx_pkts,json=rxPkts,proto3" json:"rx_pkts,omitempty"`
	RxBytes       uint64                 `protobuf:"varint,7,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	RxDrop        uint64                 `protobuf:"varint,8,opt,name=rx_drop,json=rxDrop,proto3" json:"rx_drop,omitempty"`
	RxErr         uint64                 `protobuf:"varint,9,opt,name=rx_err,json=rxErr,proto3" json:"rx_err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortStats) Reset() {
	*x = PortStats{}
	mi := &file_dataplane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortStats) ProtoMessage() {}

func (x *PortStats) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortStats.ProtoReflect.Descriptor instead.
func (*PortStats) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{6}
}

func (x *PortStats) GetPortId() uint32 {
	if x != nil {
		return x.PortId
	}
	return 0
}

func (x *PortStats) GetTxPkts() uint64 {
	if x != nil {
		return x.TxPkts
	}
	return 0
}

func (x *PortStats) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *PortStats) GetTxDrop() uint64 {
	if x != nil {
		return x.TxDrop
	}
	return 0
}

func (x *PortStats) GetTxErr() uint64 {
	if x != nil {
		return x.TxErr
	}
	return 0
}

func (x *PortStats) GetRxPkts() uint64 {
	if x != nil {
		return x.RxPkts
	}
	return 0
}

func (x *PortStats) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *PortStats) GetRxDrop() uint64 {
	if x != nil {
		return x.RxDrop
	}
	return 0
}

func (x *PortStats) GetRxErr() uint64 {
	if x != nil {
		return x.RxErr
	}
	return 0
}

type TelemetrySnapshot struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TsNs   uint64                 `protobuf:"varint,1,opt,name=ts_ns,json=tsNs,proto3" json:"ts_ns,omitempty"` // 데이터플레인 기준 시각
	NodeId string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Ports  []*PortStats           `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty"`
	// 이벤트 ring 이 가득 차 버려진 개수.
	// 이 값이 늘면 제어부가 이벤트를 충분히 빨리 소비하지 못하고 있다는 뜻이다.
	EventDrop     uint64 `protobuf:"varint,4,opt,name=event_drop,json=eventDrop,proto3" json:"event_drop,omitempty"`
	ActiveLcores  uint32 `protobuf:"varint,5,opt,name=active_lcores,json=activeLcores,proto3" json:"active_lcores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetrySnapshot) Reset() {
	*x = TelemetrySnapshot{}
	mi := &file_dataplane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetrySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetrySnapshot) ProtoMessage() {}

func (x *TelemetrySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetrySnapshot.ProtoReflect.Descriptor instead.
func (*TelemetrySnapshot) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{7}
}

func (x *TelemetrySnapshot) GetTsNs() uint64 {
	if x != nil {
		return x.TsNs
	}
	return 0
}

func (x *TelemetrySnapshot) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TelemetrySnapshot) GetPorts() []*PortStats {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *TelemetrySnapshot) GetEventDrop() uint64 {
	if x != nil {
		return x.EventDrop
	}
	return 0
}

func (x *TelemetrySnapshot) GetActiveLcores() uint32 {
	if x != nil {
		return x.ActiveLcores
	}
	return 0
}

// ─────────────────────────────────────────────────────────────
// 판정 이벤트 — C 가 µs 단위로 내린 실시간 판정 결과의 요약.
// 세션 단위 집계·룰 판정은 제어부가 이 이벤트들을 모아 수행한다.
// ─────────────────────────────────────────────────────────────
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsNs          uint64                 `protobuf:"varint,1,opt,name=ts_ns,json=tsNs,proto3" json:"ts_ns,omitempty"`
	Kind          Event_Kind             `protobuf:"varint,2,opt,name=kind,proto3,enum=mir.v1.Event_Kind" json:"kind,omitempty"`
	PortId        uint32                 `protobuf:"varint,3,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	FlowKey       string                 `protobuf:"bytes,4,opt,name=flow_key,json=flowKey,proto3" json:"flow_key,omitempty"` // "src:sport>dst:dport/proto"
	RttUs         uint32                 `protobuf:"varint,5,opt,name=rtt_us,json=rttUs,proto3" json:"rtt_us,omitempty"`
	Detail        string                 `protobuf:"bytes,6,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_dataplane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{8}
}

func (x *Event) GetTsNs() uint64 {
	if x != nil {
		return x.TsNs
	}
	return 0
}

func (x *Event) GetKind() Event_Kind {
	if x != nil {
		return x.Kind
	}
	return Event_KIND_UNSPECIFIED
}

func (x *Event) GetPortId() uint32 {
	if x != nil {
		return x.PortId
	}
	return 0
}

func (x *Event) GetFlowKey() string {
	if x != nil {
		return x.FlowKey
	}
	return ""
}

func (x *Event) GetRttUs() uint32 {
	if x != nil {
		return x.RttUs
	}
	return 0
}

func (x *Event) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type StreamTelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTelemetryRequest) Reset() {
	*x = StreamTelemetryRequest{}
	mi := &file_dataplane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTelemetryRequest) ProtoMessage() {}

func (x *StreamTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTelemetryRequest.ProtoReflect.Descriptor instead.
func (*StreamTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{9}
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_dataplane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{10}
}

var File_dataplane_proto protoreflect.FileDescriptor

const file_dataplane_proto_rawDesc = "" +
	"\n" +
	"\x0fdataplane.proto\x12\x06mir.v1\"7\n" +
	"\fHelloRequest\x12'\n" +
	"\x0fcontrol_version\x18\x01 \x01(\tR\x0econtrolVersion\"\x8b\x01\n" +
	"\bPortInfo\x12\x17\n" +
	"\aport_id\x18\x01 \x01(\rR\x06portId\x12\x16\n" +
	"\x06driver\x18\x02 \x01(\tR\x06driver\x12\x10\n" +
	"\x03mac\x18\x03 \x01(\tR\x03mac\x12\x1b\n" +
	"\tnuma_node\x18\x04 \x01(\x05R\bnumaNode\x12\x1f\n" +
	"\vdevice_spec\x18\x05 \x01(\tR\n" +
	"deviceSpec\"\xb4\x01\n" +
	"\rHelloResponse\x12+\n" +
	"\x11dataplane_version\x18\x01 \x01(\tR\x10dataplaneVersion\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12&\n" +
	"\x05ports\x18\x03 \x03(\v2\x10.mir.v1.PortInfoR\x05ports\x12\x16\n" +
	"\x06lcores\x18\x04 \x03(\rR\x06lcores\x12\x1d\n" +
	"\n" +
	"main_lcore\x18\x05 \x01(\rR\tmainLcore\"\x8e\x01\n" +
	"\x14StartScenarioRequest\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x12\x1b\n" +
	"\tpcap_path\x18\x02 \x01(\tR\bpcapPath\x12\x19\n" +
	"\brate_pps\x18\x03 \x01(\x04R\aratePps\x12\x1d\n" +
	"\n" +
	"duration_s\x18\x04 \x01(\rR\tdurationS\"6\n" +
	"\x13StopScenarioRequest\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\"/\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xec\x01\n" +
	"\tPortStats\x12\x17\n" +
	"\aport_id\x18\x01 \x01(\rR\x06portId\x12\x17\n" +
	"\atx_pkts\x18\x02 \x01(\x04R\x06txPkts\x12\x19\n" +
	"\btx_bytes\x18\x03 \x01(\x04R\atxBytes\x12\x17\n" +
	"\atx_drop\x18\x04 \x01(\x04R\x06txDrop\x12\x15\n" +
	"\x06tx_err\x18\x05 \x01(\x04R\x05txErr\x12\x17\n" +
	"\arx_pkts\x18\x06 \x01(\x04R\x06rxPkts\x12\x19\n" +
	"\brx_bytes\x18\a \x01(\x04R\arxBytes\x12\x17\n" +
	"\arx_drop\x18\b \x01(\x04R\x06rxDrop\x12\x15\n" +
	"\x06rx_err\x18\t \x01(\x04R\x05rxErr\"\xae\x01\n" +
	"\x11TelemetrySnapshot\x12\x13\n" +
	"\x05ts_ns\x18\x01 \x01(\x04R\x04tsNs\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12'\n" +
	"\x05ports\x18\x03 \x03(\v2\x11.mir.v1.PortStatsR\x05ports\x12\x1d\n" +
	"\n" +
	"event_drop\x18\x04 \x01(\x04R\teventDrop\x12#\n" +
	"\ractive_lcores\x18\x05 \x01(\rR\factiveLcores\"\xa4\x02\n" +
	"\x05Event\x12\x13\n" +
	"\x05ts_ns\x18\x01 \x01(\x04R\x04tsNs\x12&\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x12.mir.v1.Event.KindR\x04kind\x12\x17\n" +
	"\aport_id\x18\x03 \x01(\rR\x06portId\x12\x19\n" +
	"\bflow_key\x18\x04 \x01(\tR\aflowKey\x12\x15\n" +
	"\x06rtt_us\x18\x05 \x01(\rR\x05rttUs\x12\x16\n" +
	"\x06detail\x18\x06 \x01(\tR\x06detail\"{\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13KIND_SYNACK_TIMEOUT\x10\x01\x12\x15\n" +
	"\x11KIND_RST_RECEIVED\x10\x02\x12\x18\n" +
	"\x14KIND_UNEXPECTED_FLAG\x10\x03\x12\x13\n" +
	"\x0fKIND_RETRANSMIT\x10\x04\"\x18\n" +
	"\x16StreamTelemetryRequest\"\x15\n" +
	"\x13StreamEventsRequest*\xd3\x01\n" +
	"\aMsgType\x12\x18\n" +
	"\x14MSG_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16MSG_TYPE_HELLO_REQUEST\x10\x01\x12\x1b\n" +
	"\x17MSG_TYPE_START_SCENARIO\x10\x02\x12\x1a\n" +
	"\x16MSG_TYPE_STOP_SCENARIO\x10\x03\x12\x1b\n" +
	"\x17MSG_TYPE_HELLO_RESPONSE\x10e\x12\x16\n" +
	"\x12MSG_TYPE_TELEMETRY\x10f\x12\x12\n" +
	"\x0eMSG_TYPE_EVENT\x10g\x12\x10\n" +
	"\fMSG_TYPE_ACK\x10h2\xc5\x02\n" +
	"\tDataPlane\x124\n" +
	"\x05Hello\x12\x14.mir.v1.HelloRequest\x1a\x15.mir.v1.HelloResponse\x12:\n" +
	"\rStartScenario\x12\x1c.mir.v1.StartScenarioRequest\x1a\v.mir.v1.Ack\x128\n" +
	"\fStopScenario\x12\x1b.mir.v1.StopScenarioRequest\x1a\v.mir.v1.Ack\x12N\n" +
	"\x0fStreamTelemetry\x12\x1e.mir.v1.StreamTelemetryRequest\x1a\x19.mir.v1.TelemetrySnapshot0\x01\x12<\n" +
	"\fStreamEvents\x12\x1b.mir.v1.StreamEventsRequest\x1a\r.mir.v1.Event0\x01B\x14Z\x12mir/internal/pb;pbb\x06proto3"

var (
	file_dataplane_proto_rawDescOnce sync.Once
	file_dataplane_proto_rawDescData []byte
)

func file_dataplane_proto_rawDescGZIP() []byte {
	file_dataplane_proto_rawDescOnce.Do(func() {
		file_dataplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dataplane_proto_rawDesc), len(file_dataplane_proto_rawDesc)))
	})
	return file_dataplane_proto_rawDescData
}

var file_dataplane_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_dataplane_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_dataplane_proto_goTypes = []any{
	(MsgType)(0),                   // 0: mir.v1.MsgType
	(Event_Kind)(0),                // 1: mir.v1.Event.Kind
	(*HelloRequest)(nil),           // 2: mir.v1.HelloRequest
	(*PortInfo)(nil),               // 3: mir.v1.PortInfo
	(*HelloResponse)(nil),          // 4: mir.v1.HelloResponse
	(*StartScenarioRequest)(nil),   // 5: mir.v1.StartScenarioRequest
	(*StopScenarioRequest)(nil),    // 6: mir.v1.StopScenarioRequest
	(*Ack)(nil),                    // 7: mir.v1.Ack
	(*PortStats)(nil),              // 8: mir.v1.PortStats
	(*TelemetrySnapshot)(nil),      // 9: mir.v1.TelemetrySnapshot
	(*Event)(nil),                  // 10: mir.v1.Event
	(*StreamTelemetryRequest)(nil), // 11: mir.v1.StreamTelemetryRequest
	(*StreamEventsRequest)(nil),    // 12: mir.v1.StreamEventsRequest
}
var file_dataplane_proto_depIdxs = []int32{
	3,  // 0: mir.v1.HelloResponse.ports:type_name -> mir.v1.PortInfo
	8,  // 1: mir.v1.TelemetrySnapshot.ports:type_name -> mir.v1.PortStats
	1,  // 2: mir.v1.Event.kind:type_name -> mir.v1.Event.Kind
	2,  // 3: mir.v1.DataPlane.Hello:input_type -> mir.v1.HelloRequest
	5,  // 4: mir.v1.DataPlane.StartScenario:input_type -> mir.v1.StartScenarioRequest
	6,  // 5: mir.v1.DataPlane.StopScenario:input_type -> mir.v1.StopScenarioRequest
	11, // 6: mir.v1.DataPlane.StreamTelemetry:input_type -> mir.v1.StreamTelemetryRequest
	12, // 7: mir.v1.DataPlane.StreamEvents:input_type -> mir.v1.StreamEventsRequest
	4,  // 8: mir.v1.DataPlane.Hello:output_type -> mir.v1.HelloResponse
	7,  // 9: mir.v1.DataPlane.StartScenario:output_type -> mir.v1.Ack
	7,  // 10: mir.v1.DataPlane.StopScenario:output_type -> mir.v1.Ack
	9,  // 11: mir.v1.DataPlane.StreamTelemetry:output_type -> mir.v1.TelemetrySnapshot
	10, // 12: mir.v1.DataPlane.StreamEvents:output_type -> mir.v1.Event
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_dataplane_proto_init() }
func file_dataplane_proto_init() {
	if File_dataplane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dataplane_proto_rawDesc), len(file_dataplane_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dataplane_proto_goTypes,
		DependencyIndexes: file_dataplane_proto_depIdxs,
		EnumInfos:         file_dataplane_proto_enumTypes,
		MessageInfos:      file_dataplane_proto_msgTypes,
	}.Build()
	File_dataplane_proto = out.File
	file_dataplane_proto_goTypes = nil
	file_dataplane_proto_depIdxs = nil
}
