// Mir — 데이터플레인 ⇄ 제어부 공용 스키마.
//
// 이 파일 하나가 **두 hop 을 모두 정의**한다.
//
//   ③ C 데이터플레인 ⇄ Go 사이드카   : unix socket + length-prefix framing
//   ④ Go 사이드카   ⇄ Go 제어부      : gRPC (service DataPlane)
//
// 사이드카는 대부분의 필드를 그대로 통과시키는 릴레이라, 스키마를 하나로
// 유지하면 두 hop 이 갈라질 여지가 없다.
//
// ── hop ③ 와이어 포맷 (C 의 ipc_server.c 와 반드시 일치) ──────────────
//
//   +--------+--------+------------------+
//   | u32 be | u16 be |     payload      |
//   | length |  type  |    (protobuf)    |
//   +--------+--------+------------------+
//
//   length = sizeof(type) + sizeof(payload)   — 자기 자신은 제외
//   type   = MsgType 값
//
// gRPC 를 C 에 직접 넣지 않은 이유는 성능이 아니라 **스레드 격리**다.
// C 프로세스에 gRPC 스레드 풀이 생기면 컨테이너 cpuset(= worker 코어 포함)을
// 떠돌며 busy-poll 루프를 선점할 수 있다. 사이드카는 별도 컨테이너라
// 애초에 worker 코어에 올라갈 물리적 경로가 없다.
//
// ── 코드 생성 ─────────────────────────────────────────────────────────
//
//   Go : buf generate            (저장소 루트에서. 생성물은 커밋한다)
//   C  : protoc-c --proto_path=proto --c_out=<builddir> proto/dataplane.proto
//        (meson custom_target 이 빌드 중에 실행 — 이미지 빌드 시점에만 필요)
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: dataplane.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ─────────────────────────────────────────────────────────────
// hop ③ 프레임 타입 태그.
//
// enum 값 자체는 payload 에 실리지 않고 프레임 헤더의 u16 에 들어간다.
// 100 미만 = 제어부 → 데이터플레인, 100 이상 = 데이터플레인 → 제어부.
// ─────────────────────────────────────────────────────────────
type MsgType int32

const (
	MsgType_MSG_TYPE_UNSPECIFIED MsgType = 0
	// 제어부 → 데이터플레인
	MsgType_MSG_TYPE_HELLO_REQUEST  MsgType = 1
	MsgType_MSG_TYPE_START_SCENARIO MsgType = 2
	MsgType_MSG_TYPE_STOP_SCENARIO  MsgType = 3
	// 데이터플레인 → 제어부
	MsgType_MSG_TYPE_HELLO_RESPONSE MsgType = 101
	MsgType_MSG_TYPE_TELEMETRY      MsgType = 102
	MsgType_MSG_TYPE_EVENT          MsgType = 103
	MsgType_MSG_TYPE_ACK            MsgType = 104
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0:   "MSG_TYPE_UNSPECIFIED",
		1:   "MSG_TYPE_HELLO_REQUEST",
		2:   "MSG_TYPE_START_SCENARIO",
		3:   "MSG_TYPE_STOP_SCENARIO",
		101: "MSG_TYPE_HELLO_RESPONSE",
		102: "MSG_TYPE_TELEMETRY",
		103: "MSG_TYPE_EVENT",
		104: "MSG_TYPE_ACK",
	}
	MsgType_value = map[string]int32{
		"MSG_TYPE_UNSPECIFIED":    0,
		"MSG_TYPE_HELLO_REQUEST":  1,
		"MSG_TYPE_START_SCENARIO": 2,
		"MSG_TYPE_STOP_SCENARIO":  3,
		"MSG_TYPE_HELLO_RESPONSE": 101,
		"MSG_TYPE_TELEMETRY":      102,
		"MSG_TYPE_EVENT":          103,
		"MSG_TYPE_ACK":            104,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_dataplane_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_dataplane_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{0}
}

type Event_Kind int32

const (
	Event_KIND_UNSPECIFIED     Event_Kind = 0
	Event_KIND_SYNACK_TIMEOUT  Event_Kind = 1 // SYN 보냈으나 SYN-ACK 없음
	Event_KIND_RST_RECEIVED    Event_Kind = 2 // 포트 닫힘 추정
	Event_KIND_UNEXPECTED_FLAG Event_Kind = 3
	Event_KIND_RETRANSMIT      Event_Kind = 4
)

// Enum value maps for Event_Kind.
var (
	Event_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_SYNACK_TIMEOUT",
		2: "KIND_RST_RECEIVED",
		3: "KIND_UNEXPECTED_FLAG",
		4: "KIND_RETRANSMIT",
	}
	Event_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED":     0,
		"KIND_SYNACK_TIMEOUT":  1,
		"KIND_RST_RECEIVED":    2,
		"KIND_UNEXPECTED_FLAG": 3,
		"KIND_RETRANSMIT":      4,
	}
)

func (x Event_Kind) Enum() *Event_Kind {
	p := new(Event_Kind)
	*p = x
	return p
}

func (x Event_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_dataplane_proto_enumTypes[1].Descriptor()
}

func (Event_Kind) Type() protoreflect.EnumType {
	return &file_dataplane_proto_enumTypes[1]
}

func (x Event_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event_Kind.Descriptor instead.
func (Event_Kind) EnumDescriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{15, 0}
}

// ─────────────────────────────────────────────────────────────
// 핸드셰이크 — 제어부가 붙자마자 능력을 조회한다.
// ─────────────────────────────────────────────────────────────
type HelloRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ControlVersion string                 `protobuf:"bytes,1,opt,name=control_version,json=controlVersion,proto3" json:"control_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_dataplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetControlVersion() string {
	if x != nil {
		return x.ControlVersion
	}
	return ""
}

type PortInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PortId        uint32                 `protobuf:"varint,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	Driver        string                 `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty"` // "net_i40e", "net_ice", "net_ena" ...
	Mac           string                 `protobuf:"bytes,3,opt,name=mac,proto3" json:"mac,omitempty"`
	NumaNode      int32                  `protobuf:"varint,4,opt,name=numa_node,json=numaNode,proto3" json:"numa_node,omitempty"`
	DeviceSpec    string                 `protobuf:"bytes,5,opt,name=device_spec,json=deviceSpec,proto3" json:"device_spec,omitempty"` // PCI BDF 또는 MAC (환경에 따라 다름 — eal_args.h 참조)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortInfo) Reset() {
	*x = PortInfo{}
	mi := &file_dataplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortInfo) ProtoMessage() {}

func (x *PortInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortInfo.ProtoReflect.Descriptor instead.
func (*PortInfo) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{1}
}

func (x *PortInfo) GetPortId() uint32 {
	if x != nil {
		return x.PortId
	}
	return 0
}

func (x *PortInfo) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *PortInfo) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *PortInfo) GetNumaNode() int32 {
	if x != nil {
		return x.NumaNode
	}
	return 0
}

func (x *PortInfo) GetDeviceSpec() string {
	if x != nil {
		return x.DeviceSpec
	}
	return ""
}

type HelloResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DataplaneVersion string                 `protobuf:"bytes,1,opt,name=dataplane_version,json=dataplaneVersion,proto3" json:"dataplane_version,omitempty"`
	NodeId           string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // 인스턴스명 (HOSTNAME)
	Ports            []*PortInfo            `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty"`
	Lcores           []uint32               `protobuf:"varint,4,rep,packed,name=lcores,proto3" json:"lcores,omitempty"` // 실제로 할당받은 CPU 목록 (cpuset 에서 읽은 값)
	MainLcore        uint32                 `protobuf:"varint,5,opt,name=main_lcore,json=mainLcore,proto3" json:"main_lcore,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_dataplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{2}
}

func (x *HelloResponse) GetDataplaneVersion() string {
	if x != nil {
		return x.DataplaneVersion
	}
	return ""
}

func (x *HelloResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HelloResponse) GetPorts() []*PortInfo {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *HelloResponse) GetLcores() []uint32 {
	if x != nil {
		return x.Lcores
	}
	return nil
}

func (x *HelloResponse) GetMainLcore() uint32 {
	if x != nil {
		return x.MainLcore
	}
	return 0
}

// ─────────────────────────────────────────────────────────────
// 패킷 명세 (모드 A — Stateless 고속 생성)
//
// 헤더를 구조체로 기술한다. PCAP 리플레이(모드 C)는 원본 바이트를 그대로
// 재생하므로 이 경로를 쓰지 않는다 — 두 모드는 입력이 다르지 자매 관계가 아니다.
//
// **가변 필드.** 같은 패킷만 반복하면 상대의 RSS·플로우 테이블·세션 추적이
// 전부 한 엔트리로 몰려 실제 부하와 동떨어진다. `*_count` 로 값을 N개 순환시켜
// 플로우를 벌린다. 0 또는 1 이면 고정이다.
// ─────────────────────────────────────────────────────────────
type EthSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcMac        string                 `protobuf:"bytes,1,opt,name=src_mac,json=srcMac,proto3" json:"src_mac,omitempty"`  // 비우면 포트의 실제 MAC 을 쓴다
	DstMac        string                 `protobuf:"bytes,2,opt,name=dst_mac,json=dstMac,proto3" json:"dst_mac,omitempty"`  // 필수
	VlanId        uint32                 `protobuf:"varint,3,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"` // 0 = 태그 없음
	VlanPcp       uint32                 `protobuf:"varint,4,opt,name=vlan_pcp,json=vlanPcp,proto3" json:"vlan_pcp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EthSpec) Reset() {
	*x = EthSpec{}
	mi := &file_dataplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EthSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EthSpec) ProtoMessage() {}

func (x *EthSpec) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EthSpec.ProtoReflect.Descriptor instead.
func (*EthSpec) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{3}
}

func (x *EthSpec) GetSrcMac() string {
	if x != nil {
		return x.SrcMac
	}
	return ""
}

func (x *EthSpec) GetDstMac() string {
	if x != nil {
		return x.DstMac
	}
	return ""
}

func (x *EthSpec) GetVlanId() uint32 {
	if x != nil {
		return x.VlanId
	}
	return 0
}

func (x *EthSpec) GetVlanPcp() uint32 {
	if x != nil {
		return x.VlanPcp
	}
	return 0
}

type Ipv4Spec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Src   string                 `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst   string                 `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	// src 부터 N개를 순환한다 (호스트 바이트 순서로 +1). 0/1 = 고정.
	SrcCount      uint32 `protobuf:"varint,3,opt,name=src_count,json=srcCount,proto3" json:"src_count,omitempty"`
	DstCount      uint32 `protobuf:"varint,4,opt,name=dst_count,json=dstCount,proto3" json:"dst_count,omitempty"`
	Ttl           uint32 `protobuf:"varint,5,opt,name=ttl,proto3" json:"ttl,omitempty"` // 0 = 64
	Dscp          uint32 `protobuf:"varint,6,opt,name=dscp,proto3" json:"dscp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ipv4Spec) Reset() {
	*x = Ipv4Spec{}
	mi := &file_dataplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ipv4Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ipv4Spec) ProtoMessage() {}

func (x *Ipv4Spec) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ipv4Spec.ProtoReflect.Descriptor instead.
func (*Ipv4Spec) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{4}
}

func (x *Ipv4Spec) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *Ipv4Spec) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *Ipv4Spec) GetSrcCount() uint32 {
	if x != nil {
		return x.SrcCount
	}
	return 0
}

func (x *Ipv4Spec) GetDstCount() uint32 {
	if x != nil {
		return x.DstCount
	}
	return 0
}

func (x *Ipv4Spec) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *Ipv4Spec) GetDscp() uint32 {
	if x != nil {
		return x.Dscp
	}
	return 0
}

// Phase 2 에서는 **거부한다.** 스키마를 지금 잡아 두는 이유는 나중에 oneof 에
// 끼워 넣으면 두 hop 의 생성 코드를 다시 만들어야 하기 때문이다.
type Ipv6Spec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           string                 `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst           string                 `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	SrcCount      uint32                 `protobuf:"varint,3,opt,name=src_count,json=srcCount,proto3" json:"src_count,omitempty"`
	DstCount      uint32                 `protobuf:"varint,4,opt,name=dst_count,json=dstCount,proto3" json:"dst_count,omitempty"`
	HopLimit      uint32                 `protobuf:"varint,5,opt,name=hop_limit,json=hopLimit,proto3" json:"hop_limit,omitempty"`
	TrafficClass  uint32                 `protobuf:"varint,6,opt,name=traffic_class,json=trafficClass,proto3" json:"traffic_class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ipv6Spec) Reset() {
	*x = Ipv6Spec{}
	mi := &file_dataplane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ipv6Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ipv6Spec) ProtoMessage() {}

func (x *Ipv6Spec) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ipv6Spec.ProtoReflect.Descriptor instead.
func (*Ipv6Spec) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{5}
}

func (x *Ipv6Spec) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *Ipv6Spec) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *Ipv6Spec) GetSrcCount() uint32 {
	if x != nil {
		return x.SrcCount
	}
	return 0
}

func (x *Ipv6Spec) GetDstCount() uint32 {
	if x != nil {
		return x.DstCount
	}
	return 0
}

func (x *Ipv6Spec) GetHopLimit() uint32 {
	if x != nil {
		return x.HopLimit
	}
	return 0
}

func (x *Ipv6Spec) GetTrafficClass() uint32 {
	if x != nil {
		return x.TrafficClass
	}
	return 0
}

type TcpSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcPort       uint32                 `protobuf:"varint,1,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstPort       uint32                 `protobuf:"varint,2,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	SrcPortCount  uint32                 `protobuf:"varint,3,opt,name=src_port_count,json=srcPortCount,proto3" json:"src_port_count,omitempty"`
	DstPortCount  uint32                 `protobuf:"varint,4,opt,name=dst_port_count,json=dstPortCount,proto3" json:"dst_port_count,omitempty"`
	Flags         uint32                 `protobuf:"varint,5,opt,name=flags,proto3" json:"flags,omitempty"`   // RTE_TCP_*_FLAG 비트합. 0 = SYN
	Window        uint32                 `protobuf:"varint,6,opt,name=window,proto3" json:"window,omitempty"` // 0 = 65535
	Seq           uint32                 `protobuf:"varint,7,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TcpSpec) Reset() {
	*x = TcpSpec{}
	mi := &file_dataplane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcpSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpSpec) ProtoMessage() {}

func (x *TcpSpec) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpSpec.ProtoReflect.Descriptor instead.
func (*TcpSpec) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{6}
}

func (x *TcpSpec) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *TcpSpec) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *TcpSpec) GetSrcPortCount() uint32 {
	if x != nil {
		return x.SrcPortCount
	}
	return 0
}

func (x *TcpSpec) GetDstPortCount() uint32 {
	if x != nil {
		return x.DstPortCount
	}
	return 0
}

func (x *TcpSpec) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *TcpSpec) GetWindow() uint32 {
	if x != nil {
		return x.Window
	}
	return 0
}

func (x *TcpSpec) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type UdpSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcPort       uint32                 `protobuf:"varint,1,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstPort       uint32                 `protobuf:"varint,2,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	SrcPortCount  uint32                 `protobuf:"varint,3,opt,name=src_port_count,json=srcPortCount,proto3" json:"src_port_count,omitempty"`
	DstPortCount  uint32                 `protobuf:"varint,4,opt,name=dst_port_count,json=dstPortCount,proto3" json:"dst_port_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UdpSpec) Reset() {
	*x = UdpSpec{}
	mi := &file_dataplane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UdpSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UdpSpec) ProtoMessage() {}

func (x *UdpSpec) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UdpSpec.ProtoReflect.Descriptor instead.
func (*UdpSpec) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{7}
}

func (x *UdpSpec) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *UdpSpec) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *UdpSpec) GetSrcPortCount() uint32 {
	if x != nil {
		return x.SrcPortCount
	}
	return 0
}

func (x *UdpSpec) GetDstPortCount() uint32 {
	if x != nil {
		return x.DstPortCount
	}
	return 0
}

type PacketSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Eth   *EthSpec               `protobuf:"bytes,1,opt,name=eth,proto3" json:"eth,omitempty"`
	// Types that are valid to be assigned to L3:
	//
	//	*PacketSpec_Ipv4
	//	*PacketSpec_Ipv6
	L3 isPacketSpec_L3 `protobuf_oneof:"l3"`
	// Types that are valid to be assigned to L4:
	//
	//	*PacketSpec_Tcp
	//	*PacketSpec_Udp
	L4 isPacketSpec_L4 `protobuf_oneof:"l4"`
	// CRC 를 제외한 전체 프레임 길이. 0 이면 헤더 합.
	// 이더넷 최소 프레임 규정 때문에 64 미만은 64 로 올린다 — 그보다 작은
	// 프레임은 선로에 존재할 수 없다.
	FrameSize uint32 `protobuf:"varint,6,opt,name=frame_size,json=frameSize,proto3" json:"frame_size,omitempty"`
	// 비우면 남는 자리를 패턴으로 채운다. 지정하면 그대로 싣되 frame_size 를 넘지 않는다.
	Payload       []byte `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketSpec) Reset() {
	*x = PacketSpec{}
	mi := &file_dataplane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketSpec) ProtoMessage() {}

func (x *PacketSpec) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketSpec.ProtoReflect.Descriptor instead.
func (*PacketSpec) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{8}
}

func (x *PacketSpec) GetEth() *EthSpec {
	if x != nil {
		return x.Eth
	}
	return nil
}

func (x *PacketSpec) GetL3() isPacketSpec_L3 {
	if x != nil {
		return x.L3
	}
	return nil
}

func (x *PacketSpec) GetIpv4() *Ipv4Spec {
	if x != nil {
		if x, ok := x.L3.(*PacketSpec_Ipv4); ok {
			return x.Ipv4
		}
	}
	return nil
}

func (x *PacketSpec) GetIpv6() *Ipv6Spec {
	if x != nil {
		if x, ok := x.L3.(*PacketSpec_Ipv6); ok {
			return x.Ipv6
		}
	}
	return nil
}

func (x *PacketSpec) GetL4() isPacketSpec_L4 {
	if x != nil {
		return x.L4
	}
	return nil
}

func (x *PacketSpec) GetTcp() *TcpSpec {
	if x != nil {
		if x, ok := x.L4.(*PacketSpec_Tcp); ok {
			return x.Tcp
		}
	}
	return nil
}

func (x *PacketSpec) GetUdp() *UdpSpec {
	if x != nil {
		if x, ok := x.L4.(*PacketSpec_Udp); ok {
			return x.Udp
		}
	}
	return nil
}

func (x *PacketSpec) GetFrameSize() uint32 {
	if x != nil {
		return x.FrameSize
	}
	return 0
}

func (x *PacketSpec) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type isPacketSpec_L3 interface {
	isPacketSpec_L3()
}

type PacketSpec_Ipv4 struct {
	Ipv4 *Ipv4Spec `protobuf:"bytes,2,opt,name=ipv4,proto3,oneof"`
}

type PacketSpec_Ipv6 struct {
	Ipv6 *Ipv6Spec `protobuf:"bytes,3,opt,name=ipv6,proto3,oneof"`
}

func (*PacketSpec_Ipv4) isPacketSpec_L3() {}

func (*PacketSpec_Ipv6) isPacketSpec_L3() {}

type isPacketSpec_L4 interface {
	isPacketSpec_L4()
}

type PacketSpec_Tcp struct {
	Tcp *TcpSpec `protobuf:"bytes,4,opt,name=tcp,proto3,oneof"`
}

type PacketSpec_Udp struct {
	Udp *UdpSpec `protobuf:"bytes,5,opt,name=udp,proto3,oneof"`
}

func (*PacketSpec_Tcp) isPacketSpec_L4() {}

func (*PacketSpec_Udp) isPacketSpec_L4() {}

// ─────────────────────────────────────────────────────────────
// 명령
// ─────────────────────────────────────────────────────────────
type StartScenarioRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	// 리플레이 대상 PCAP. **파일 내용이 아니라 경로만** 전달한다.
	// GB 단위일 수 있으므로 제어 채널로 실어 보내지 않고 공유 볼륨을 경유한다.
	// 제어부가 RW 로, 데이터플레인이 RO 로 같은 볼륨을 마운트한다.
	PcapPath  string `protobuf:"bytes,2,opt,name=pcap_path,json=pcapPath,proto3" json:"pcap_path,omitempty"`
	RatePps   uint64 `protobuf:"varint,3,opt,name=rate_pps,json=ratePps,proto3" json:"rate_pps,omitempty"`       // 0 = 최대 속도
	DurationS uint32 `protobuf:"varint,4,opt,name=duration_s,json=durationS,proto3" json:"duration_s,omitempty"` // 0 = 무한
	// 송신 시작 시각 (CLOCK_REALTIME 기준 ns). 0 = 즉시.
	//
	// 장비 여러 대가 **동시에** 송신을 시작해야 하는 시나리오를 위한 것이다.
	// 제어부가 각 인스턴스에 명령을 뿌리는 데는 왕복 지연이 있으므로, "받는 즉시"
	// 로는 장비 간 시작 시점이 수 ms 어긋난다. 공통 시각을 지정해 그 편차를 없앤다.
	//
	// ★ 이 값은 **장비 간 시계가 동기화돼 있을 때만** 의미가 있다. PTP 가
	//
	//	전제이고, 텔레메트리의 ts_ns 도 같은 시계를 쓴다 → deploy/host/60-ptp.md
	StartAtNs uint64 `protobuf:"varint,5,opt,name=start_at_ns,json=startAtNs,proto3" json:"start_at_ns,omitempty"`
	// 모드 A — 생성할 패킷의 명세. pcap_path 와 **배타**다.
	// 둘 다 비면 거부한다(무엇을 보낼지 알 수 없다).
	Packet *PacketSpec `protobuf:"bytes,6,opt,name=packet,proto3" json:"packet,omitempty"`
	// 송신에 쓸 worker lcore 수. 0 = 가용한 전부.
	//
	// 라인레이트에 필요한 코어 수는 프레임 크기와 NIC 에 따라 크게 달라져서
	// 실측 없이는 정할 수 없다. 이 값을 낮춰 가며 재는 것이 Phase 7 튜닝의
	// 출발점이므로 명령 단위로 조절할 수 있어야 한다.
	TxLcores      uint32 `protobuf:"varint,7,opt,name=tx_lcores,json=txLcores,proto3" json:"tx_lcores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartScenarioRequest) Reset() {
	*x = StartScenarioRequest{}
	mi := &file_dataplane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartScenarioRequest) ProtoMessage() {}

func (x *StartScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartScenarioRequest.ProtoReflect.Descriptor instead.
func (*StartScenarioRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{9}
}

func (x *StartScenarioRequest) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *StartScenarioRequest) GetPcapPath() string {
	if x != nil {
		return x.PcapPath
	}
	return ""
}

func (x *StartScenarioRequest) GetRatePps() uint64 {
	if x != nil {
		return x.RatePps
	}
	return 0
}

func (x *StartScenarioRequest) GetDurationS() uint32 {
	if x != nil {
		return x.DurationS
	}
	return 0
}

func (x *StartScenarioRequest) GetStartAtNs() uint64 {
	if x != nil {
		return x.StartAtNs
	}
	return 0
}

func (x *StartScenarioRequest) GetPacket() *PacketSpec {
	if x != nil {
		return x.Packet
	}
	return nil
}

func (x *StartScenarioRequest) GetTxLcores() uint32 {
	if x != nil {
		return x.TxLcores
	}
	return 0
}

type StopScenarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId    string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopScenarioRequest) Reset() {
	*x = StopScenarioRequest{}
	mi := &file_dataplane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopScenarioRequest) ProtoMessage() {}

func (x *StopScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopScenarioRequest.ProtoReflect.Descriptor instead.
func (*StopScenarioRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{10}
}

func (x *StopScenarioRequest) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_dataplane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{11}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ─────────────────────────────────────────────────────────────
// 텔레메트리 — 100ms 주기 push.
//
// 개별 패킷(mbuf)은 절대 이 채널을 넘지 않는다. 148 Mpps 를 프로세스 경계
// 밖으로 내보내는 건 성립하지 않는다. worker lcore 가 per-lcore 카운터에
// 누적한 것을 제어 스레드가 합산해 스냅샷으로만 올린다.
// ─────────────────────────────────────────────────────────────
type PortStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PortId        uint32                 `protobuf:"varint,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	TxPkts        uint64                 `protobuf:"varint,2,opt,name=tx_pkts,json=txPkts,proto3" json:"tx_pkts,omitempty"`
	TxBytes       uint64                 `protobuf:"varint,3,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	TxDrop        uint64                 `protobuf:"varint,4,opt,name=tx_drop,json=txDrop,proto3" json:"tx_drop,omitempty"`
	TxErr         uint64                 `protobuf:"varint,5,opt,name=tx_err,json=txErr,proto3" json:"tx_err,omitempty"`
	RxPkts        uint64                 `protobuf:"varint,6,opt,name=rx_pkts,json=rxPkts,proto3" json:"rx_pkts,omitempty"`
	RxBytes       uint64                 `protobuf:"varint,7,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	RxDrop        uint64                 `protobuf:"varint,8,opt,name=rx_drop,json=rxDrop,proto3" json:"rx_drop,omitempty"`
	RxErr         uint64                 `protobuf:"varint,9,opt,name=rx_err,json=rxErr,proto3" json:"rx_err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortStats) Reset() {
	*x = PortStats{}
	mi := &file_dataplane_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortStats) ProtoMessage() {}

func (x *PortStats) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortStats.ProtoReflect.Descriptor instead.
func (*PortStats) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{12}
}

func (x *PortStats) GetPortId() uint32 {
	if x != nil {
		return x.PortId
	}
	return 0
}

func (x *PortStats) GetTxPkts() uint64 {
	if x != nil {
		return x.TxPkts
	}
	return 0
}

func (x *PortStats) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *PortStats) GetTxDrop() uint64 {
	if x != nil {
		return x.TxDrop
	}
	return 0
}

func (x *PortStats) GetTxErr() uint64 {
	if x != nil {
		return x.TxErr
	}
	return 0
}

func (x *PortStats) GetRxPkts() uint64 {
	if x != nil {
		return x.RxPkts
	}
	return 0
}

func (x *PortStats) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *PortStats) GetRxDrop() uint64 {
	if x != nil {
		return x.RxDrop
	}
	return 0
}

func (x *PortStats) GetRxErr() uint64 {
	if x != nil {
		return x.RxErr
	}
	return 0
}

type TelemetrySnapshot struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TsNs   uint64                 `protobuf:"varint,1,opt,name=ts_ns,json=tsNs,proto3" json:"ts_ns,omitempty"` // 데이터플레인 기준 시각
	NodeId string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Ports  []*PortStats           `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty"`
	// 이벤트 ring 이 가득 차 버려진 개수.
	// 이 값이 늘면 제어부가 이벤트를 충분히 빨리 소비하지 못하고 있다는 뜻이다.
	EventDrop    uint64 `protobuf:"varint,4,opt,name=event_drop,json=eventDrop,proto3" json:"event_drop,omitempty"`
	ActiveLcores uint32 `protobuf:"varint,5,opt,name=active_lcores,json=activeLcores,proto3" json:"active_lcores,omitempty"`
	// 진행 중인 시나리오. 비어 있으면 유휴다.
	//
	// 포트 카운터만으로는 "누가 시켜서 나가는 트래픽인지" 알 수 없다. 제어부가
	// 명령한 것과 실제로 도는 것을 대조하려면 데이터플레인이 스스로 무엇을 하고
	// 있다고 생각하는지를 올려야 한다.
	ActiveScenario string `protobuf:"bytes,6,opt,name=active_scenario,json=activeScenario,proto3" json:"active_scenario,omitempty"`
	TxLcores       uint32 `protobuf:"varint,7,opt,name=tx_lcores,json=txLcores,proto3" json:"tx_lcores,omitempty"` // 그 시나리오가 실제로 쓰는 worker 수
	// worker 가 tx_burst 에 넣지 못해 버린 패킷 누계.
	// 이 값이 늘면 NIC 이 요구 속도를 못 따라가고 있다는 뜻이다.
	TxDrop uint64 `protobuf:"varint,8,opt,name=tx_drop,json=txDrop,proto3" json:"tx_drop,omitempty"`
	// 수신 분류 (RX lcore 가 프레임을 파싱해 집계).
	//
	// **개별 응답 패킷은 경계를 넘지 않는다.** SYN 홍수에 상대가 초당 수백만
	// SYN-ACK 를 돌려줘도 그걸 하나씩 올리는 건 성립하지 않는다. 그래서 판정은
	// 여기 카운터로 집계하고, 이벤트(Event)는 이상동작만 표본으로 올린다.
	Rx            *RxClass `protobuf:"bytes,9,opt,name=rx,proto3" json:"rx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetrySnapshot) Reset() {
	*x = TelemetrySnapshot{}
	mi := &file_dataplane_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetrySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetrySnapshot) ProtoMessage() {}

func (x *TelemetrySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetrySnapshot.ProtoReflect.Descriptor instead.
func (*TelemetrySnapshot) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{13}
}

func (x *TelemetrySnapshot) GetTsNs() uint64 {
	if x != nil {
		return x.TsNs
	}
	return 0
}

func (x *TelemetrySnapshot) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TelemetrySnapshot) GetPorts() []*PortStats {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *TelemetrySnapshot) GetEventDrop() uint64 {
	if x != nil {
		return x.EventDrop
	}
	return 0
}

func (x *TelemetrySnapshot) GetActiveLcores() uint32 {
	if x != nil {
		return x.ActiveLcores
	}
	return 0
}

func (x *TelemetrySnapshot) GetActiveScenario() string {
	if x != nil {
		return x.ActiveScenario
	}
	return ""
}

func (x *TelemetrySnapshot) GetTxLcores() uint32 {
	if x != nil {
		return x.TxLcores
	}
	return 0
}

func (x *TelemetrySnapshot) GetTxDrop() uint64 {
	if x != nil {
		return x.TxDrop
	}
	return 0
}

func (x *TelemetrySnapshot) GetRx() *RxClass {
	if x != nil {
		return x.Rx
	}
	return nil
}

// TCP 플래그별 수신 분류. handshake 검증의 1차 지표다.
//
//	포트 열림  → SYN 홍수에 syn_ack 가 오른다
//	포트 닫힘  → rst 가 오른다
//	무응답     → 둘 다 그대로 (SYN-ACK timeout 판정은 흐름 상태가 필요한 Phase 4)
type RxClass struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TcpSyn        uint64                 `protobuf:"varint,1,opt,name=tcp_syn,json=tcpSyn,proto3" json:"tcp_syn,omitempty"`            // SYN only (우리 쪽으로 걸어오는 연결 시도)
	TcpSynAck     uint64                 `protobuf:"varint,2,opt,name=tcp_syn_ack,json=tcpSynAck,proto3" json:"tcp_syn_ack,omitempty"` // SYN+ACK (우리 SYN 에 대한 응답 — 포트 열림)
	TcpRst        uint64                 `protobuf:"varint,3,opt,name=tcp_rst,json=tcpRst,proto3" json:"tcp_rst,omitempty"`            // RST (포트 닫힘 / 거부)
	TcpFin        uint64                 `protobuf:"varint,4,opt,name=tcp_fin,json=tcpFin,proto3" json:"tcp_fin,omitempty"`            // FIN 포함
	TcpAck        uint64                 `protobuf:"varint,5,opt,name=tcp_ack,json=tcpAck,proto3" json:"tcp_ack,omitempty"`            // ACK only (데이터/핸드셰이크 3단계)
	TcpOther      uint64                 `protobuf:"varint,6,opt,name=tcp_other,json=tcpOther,proto3" json:"tcp_other,omitempty"`      // 위 어디에도 안 맞는 플래그 조합
	Udp           uint64                 `protobuf:"varint,7,opt,name=udp,proto3" json:"udp,omitempty"`
	NonIp         uint64                 `protobuf:"varint,8,opt,name=non_ip,json=nonIp,proto3" json:"non_ip,omitempty"` // ARP 등 비 IPv4
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RxClass) Reset() {
	*x = RxClass{}
	mi := &file_dataplane_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RxClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RxClass) ProtoMessage() {}

func (x *RxClass) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RxClass.ProtoReflect.Descriptor instead.
func (*RxClass) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{14}
}

func (x *RxClass) GetTcpSyn() uint64 {
	if x != nil {
		return x.TcpSyn
	}
	return 0
}

func (x *RxClass) GetTcpSynAck() uint64 {
	if x != nil {
		return x.TcpSynAck
	}
	return 0
}

func (x *RxClass) GetTcpRst() uint64 {
	if x != nil {
		return x.TcpRst
	}
	return 0
}

func (x *RxClass) GetTcpFin() uint64 {
	if x != nil {
		return x.TcpFin
	}
	return 0
}

func (x *RxClass) GetTcpAck() uint64 {
	if x != nil {
		return x.TcpAck
	}
	return 0
}

func (x *RxClass) GetTcpOther() uint64 {
	if x != nil {
		return x.TcpOther
	}
	return 0
}

func (x *RxClass) GetUdp() uint64 {
	if x != nil {
		return x.Udp
	}
	return 0
}

func (x *RxClass) GetNonIp() uint64 {
	if x != nil {
		return x.NonIp
	}
	return 0
}

// ─────────────────────────────────────────────────────────────
// 판정 이벤트 — C 가 µs 단위로 내린 실시간 판정 결과의 요약.
// 세션 단위 집계·룰 판정은 제어부가 이 이벤트들을 모아 수행한다.
// ─────────────────────────────────────────────────────────────
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsNs          uint64                 `protobuf:"varint,1,opt,name=ts_ns,json=tsNs,proto3" json:"ts_ns,omitempty"`
	Kind          Event_Kind             `protobuf:"varint,2,opt,name=kind,proto3,enum=mir.v1.Event_Kind" json:"kind,omitempty"`
	PortId        uint32                 `protobuf:"varint,3,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	FlowKey       string                 `protobuf:"bytes,4,opt,name=flow_key,json=flowKey,proto3" json:"flow_key,omitempty"` // "src:sport>dst:dport/proto"
	RttUs         uint32                 `protobuf:"varint,5,opt,name=rtt_us,json=rttUs,proto3" json:"rtt_us,omitempty"`
	Detail        string                 `protobuf:"bytes,6,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_dataplane_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{15}
}

func (x *Event) GetTsNs() uint64 {
	if x != nil {
		return x.TsNs
	}
	return 0
}

func (x *Event) GetKind() Event_Kind {
	if x != nil {
		return x.Kind
	}
	return Event_KIND_UNSPECIFIED
}

func (x *Event) GetPortId() uint32 {
	if x != nil {
		return x.PortId
	}
	return 0
}

func (x *Event) GetFlowKey() string {
	if x != nil {
		return x.FlowKey
	}
	return ""
}

func (x *Event) GetRttUs() uint32 {
	if x != nil {
		return x.RttUs
	}
	return 0
}

func (x *Event) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type StreamTelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTelemetryRequest) Reset() {
	*x = StreamTelemetryRequest{}
	mi := &file_dataplane_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTelemetryRequest) ProtoMessage() {}

func (x *StreamTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTelemetryRequest.ProtoReflect.Descriptor instead.
func (*StreamTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{16}
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_dataplane_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataplane_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_dataplane_proto_rawDescGZIP(), []int{17}
}

var File_dataplane_proto protoreflect.FileDescriptor

const file_dataplane_proto_rawDesc = "" +
	"\n" +
	"\x0fdataplane.proto\x12\x06mir.v1\"7\n" +
	"\fHelloRequest\x12'\n" +
	"\x0fcontrol_version\x18\x01 \x01(\tR\x0econtrolVersion\"\x8b\x01\n" +
	"\bPortInfo\x12\x17\n" +
	"\aport_id\x18\x01 \x01(\rR\x06portId\x12\x16\n" +
	"\x06driver\x18\x02 \x01(\tR\x06driver\x12\x10\n" +
	"\x03mac\x18\x03 \x01(\tR\x03mac\x12\x1b\n" +
	"\tnuma_node\x18\x04 \x01(\x05R\bnumaNode\x12\x1f\n" +
	"\vdevice_spec\x18\x05 \x01(\tR\n" +
	"deviceSpec\"\xb4\x01\n" +
	"\rHelloResponse\x12+\n" +
	"\x11dataplane_version\x18\x01 \x01(\tR\x10dataplaneVersion\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12&\n" +
	"\x05ports\x18\x03 \x03(\v2\x10.mir.v1.PortInfoR\x05ports\x12\x16\n" +
	"\x06lcores\x18\x04 \x03(\rR\x06lcores\x12\x1d\n" +
	"\n" +
	"main_lcore\x18\x05 \x01(\rR\tmainLcore\"o\n" +
	"\aEthSpec\x12\x17\n" +
	"\asrc_mac\x18\x01 \x01(\tR\x06srcMac\x12\x17\n" +
	"\adst_mac\x18\x02 \x01(\tR\x06dstMac\x12\x17\n" +
	"\avlan_id\x18\x03 \x01(\rR\x06vlanId\x12\x19\n" +
	"\bvlan_pcp\x18\x04 \x01(\rR\avlanPcp\"\x8e\x01\n" +
	"\bIpv4Spec\x12\x10\n" +
	"\x03src\x18\x01 \x01(\tR\x03src\x12\x10\n" +
	"\x03dst\x18\x02 \x01(\tR\x03dst\x12\x1b\n" +
	"\tsrc_count\x18\x03 \x01(\rR\bsrcCount\x12\x1b\n" +
	"\tdst_count\x18\x04 \x01(\rR\bdstCount\x12\x10\n" +
	"\x03ttl\x18\x05 \x01(\rR\x03ttl\x12\x12\n" +
	"\x04dscp\x18\x06 \x01(\rR\x04dscp\"\xaa\x01\n" +
	"\bIpv6Spec\x12\x10\n" +
	"\x03src\x18\x01 \x01(\tR\x03src\x12\x10\n" +
	"\x03dst\x18\x02 \x01(\tR\x03dst\x12\x1b\n" +
	"\tsrc_count\x18\x03 \x01(\rR\bsrcCount\x12\x1b\n" +
	"\tdst_count\x18\x04 \x01(\rR\bdstCount\x12\x1b\n" +
	"\thop_limit\x18\x05 \x01(\rR\bhopLimit\x12#\n" +
	"\rtraffic_class\x18\x06 \x01(\rR\ftrafficClass\"\xcb\x01\n" +
	"\aTcpSpec\x12\x19\n" +
	"\bsrc_port\x18\x01 \x01(\rR\asrcPort\x12\x19\n" +
	"\bdst_port\x18\x02 \x01(\rR\adstPort\x12$\n" +
	"\x0esrc_port_count\x18\x03 \x01(\rR\fsrcPortCount\x12$\n" +
	"\x0edst_port_count\x18\x04 \x01(\rR\fdstPortCount\x12\x14\n" +
	"\x05flags\x18\x05 \x01(\rR\x05flags\x12\x16\n" +
	"\x06window\x18\x06 \x01(\rR\x06window\x12\x10\n" +
	"\x03seq\x18\a \x01(\rR\x03seq\"\x8b\x01\n" +
	"\aUdpSpec\x12\x19\n" +
	"\bsrc_port\x18\x01 \x01(\rR\asrcPort\x12\x19\n" +
	"\bdst_port\x18\x02 \x01(\rR\adstPort\x12$\n" +
	"\x0esrc_port_count\x18\x03 \x01(\rR\fsrcPortCount\x12$\n" +
	"\x0edst_port_count\x18\x04 \x01(\rR\fdstPortCount\"\x8e\x02\n" +
	"\n" +
	"PacketSpec\x12!\n" +
	"\x03eth\x18\x01 \x01(\v2\x0f.mir.v1.EthSpecR\x03eth\x12&\n" +
	"\x04ipv4\x18\x02 \x01(\v2\x10.mir.v1.Ipv4SpecH\x00R\x04ipv4\x12&\n" +
	"\x04ipv6\x18\x03 \x01(\v2\x10.mir.v1.Ipv6SpecH\x00R\x04ipv6\x12#\n" +
	"\x03tcp\x18\x04 \x01(\v2\x0f.mir.v1.TcpSpecH\x01R\x03tcp\x12#\n" +
	"\x03udp\x18\x05 \x01(\v2\x0f.mir.v1.UdpSpecH\x01R\x03udp\x12\x1d\n" +
	"\n" +
	"frame_size\x18\x06 \x01(\rR\tframeSize\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayloadB\x04\n" +
	"\x02l3B\x04\n" +
	"\x02l4\"\xf7\x01\n" +
	"\x14StartScenarioRequest\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x12\x1b\n" +
	"\tpcap_path\x18\x02 \x01(\tR\bpcapPath\x12\x19\n" +
	"\brate_pps\x18\x03 \x01(\x04R\aratePps\x12\x1d\n" +
	"\n" +
	"duration_s\x18\x04 \x01(\rR\tdurationS\x12\x1e\n" +
	"\vstart_at_ns\x18\x05 \x01(\x04R\tstartAtNs\x12*\n" +
	"\x06packet\x18\x06 \x01(\v2\x12.mir.v1.PacketSpecR\x06packet\x12\x1b\n" +
	"\ttx_lcores\x18\a \x01(\rR\btxLcores\"6\n" +
	"\x13StopScenarioRequest\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\"/\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xec\x01\n" +
	"\tPortStats\x12\x17\n" +
	"\aport_id\x18\x01 \x01(\rR\x06portId\x12\x17\n" +
	"\atx_pkts\x18\x02 \x01(\x04R\x06txPkts\x12\x19\n" +
	"\btx_bytes\x18\x03 \x01(\x04R\atxBytes\x12\x17\n" +
	"\atx_drop\x18\x04 \x01(\x04R\x06txDrop\x12\x15\n" +
	"\x06tx_err\x18\x05 \x01(\x04R\x05txErr\x12\x17\n" +
	"\arx_pkts\x18\x06 \x01(\x04R\x06rxPkts\x12\x19\n" +
	"\brx_bytes\x18\a \x01(\x04R\arxBytes\x12\x17\n" +
	"\arx_drop\x18\b \x01(\x04R\x06rxDrop\x12\x15\n" +
	"\x06rx_err\x18\t \x01(\x04R\x05rxErr\"\xae\x02\n" +
	"\x11TelemetrySnapshot\x12\x13\n" +
	"\x05ts_ns\x18\x01 \x01(\x04R\x04tsNs\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12'\n" +
	"\x05ports\x18\x03 \x03(\v2\x11.mir.v1.PortStatsR\x05ports\x12\x1d\n" +
	"\n" +
	"event_drop\x18\x04 \x01(\x04R\teventDrop\x12#\n" +
	"\ractive_lcores\x18\x05 \x01(\rR\factiveLcores\x12'\n" +
	"\x0factive_scenario\x18\x06 \x01(\tR\x0eactiveScenario\x12\x1b\n" +
	"\ttx_lcores\x18\a \x01(\rR\btxLcores\x12\x17\n" +
	"\atx_drop\x18\b \x01(\x04R\x06txDrop\x12\x1f\n" +
	"\x02rx\x18\t \x01(\v2\x0f.mir.v1.RxClassR\x02rx\"\xd3\x01\n" +
	"\aRxClass\x12\x17\n" +
	"\atcp_syn\x18\x01 \x01(\x04R\x06tcpSyn\x12\x1e\n" +
	"\vtcp_syn_ack\x18\x02 \x01(\x04R\ttcpSynAck\x12\x17\n" +
	"\atcp_rst\x18\x03 \x01(\x04R\x06tcpRst\x12\x17\n" +
	"\atcp_fin\x18\x04 \x01(\x04R\x06tcpFin\x12\x17\n" +
	"\atcp_ack\x18\x05 \x01(\x04R\x06tcpAck\x12\x1b\n" +
	"\ttcp_other\x18\x06 \x01(\x04R\btcpOther\x12\x10\n" +
	"\x03udp\x18\a \x01(\x04R\x03udp\x12\x15\n" +
	"\x06non_ip\x18\b \x01(\x04R\x05nonIp\"\xa4\x02\n" +
	"\x05Event\x12\x13\n" +
	"\x05ts_ns\x18\x01 \x01(\x04R\x04tsNs\x12&\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x12.mir.v1.Event.KindR\x04kind\x12\x17\n" +
	"\aport_id\x18\x03 \x01(\rR\x06portId\x12\x19\n" +
	"\bflow_key\x18\x04 \x01(\tR\aflowKey\x12\x15\n" +
	"\x06rtt_us\x18\x05 \x01(\rR\x05rttUs\x12\x16\n" +
	"\x06detail\x18\x06 \x01(\tR\x06detail\"{\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13KIND_SYNACK_TIMEOUT\x10\x01\x12\x15\n" +
	"\x11KIND_RST_RECEIVED\x10\x02\x12\x18\n" +
	"\x14KIND_UNEXPECTED_FLAG\x10\x03\x12\x13\n" +
	"\x0fKIND_RETRANSMIT\x10\x04\"\x18\n" +
	"\x16StreamTelemetryRequest\"\x15\n" +
	"\x13StreamEventsRequest*\xd3\x01\n" +
	"\aMsgType\x12\x18\n" +
	"\x14MSG_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16MSG_TYPE_HELLO_REQUEST\x10\x01\x12\x1b\n" +
	"\x17MSG_TYPE_START_SCENARIO\x10\x02\x12\x1a\n" +
	"\x16MSG_TYPE_STOP_SCENARIO\x10\x03\x12\x1b\n" +
	"\x17MSG_TYPE_HELLO_RESPONSE\x10e\x12\x16\n" +
	"\x12MSG_TYPE_TELEMETRY\x10f\x12\x12\n" +
	"\x0eMSG_TYPE_EVENT\x10g\x12\x10\n" +
	"\fMSG_TYPE_ACK\x10h2\xc5\x02\n" +
	"\tDataPlane\x124\n" +
	"\x05Hello\x12\x14.mir.v1.HelloRequest\x1a\x15.mir.v1.HelloResponse\x12:\n" +
	"\rStartScenario\x12\x1c.mir.v1.StartScenarioRequest\x1a\v.mir.v1.Ack\x128\n" +
	"\fStopScenario\x12\x1b.mir.v1.StopScenarioRequest\x1a\v.mir.v1.Ack\x12N\n" +
	"\x0fStreamTelemetry\x12\x1e.mir.v1.StreamTelemetryRequest\x1a\x19.mir.v1.TelemetrySnapshot0\x01\x12<\n" +
	"\fStreamEvents\x12\x1b.mir.v1.StreamEventsRequest\x1a\r.mir.v1.Event0\x01B\x14Z\x12mir/internal/pb;pbb\x06proto3"

var (
	file_dataplane_proto_rawDescOnce sync.Once
	file_dataplane_proto_rawDescData []byte
)

func file_dataplane_proto_rawDescGZIP() []byte {
	file_dataplane_proto_rawDescOnce.Do(func() {
		file_dataplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dataplane_proto_rawDesc), len(file_dataplane_proto_rawDesc)))
	})
	return file_dataplane_proto_rawDescData
}

var file_dataplane_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_dataplane_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_dataplane_proto_goTypes = []any{
	(MsgType)(0),                   // 0: mir.v1.MsgType
	(Event_Kind)(0),                // 1: mir.v1.Event.Kind
	(*HelloRequest)(nil),           // 2: mir.v1.HelloRequest
	(*PortInfo)(nil),               // 3: mir.v1.PortInfo
	(*HelloResponse)(nil),          // 4: mir.v1.HelloResponse
	(*EthSpec)(nil),                // 5: mir.v1.EthSpec
	(*Ipv4Spec)(nil),               // 6: mir.v1.Ipv4Spec
	(*Ipv6Spec)(nil),               // 7: mir.v1.Ipv6Spec
	(*TcpSpec)(nil),                // 8: mir.v1.TcpSpec
	(*UdpSpec)(nil),                // 9: mir.v1.UdpSpec
	(*PacketSpec)(nil),             // 10: mir.v1.PacketSpec
	(*StartScenarioRequest)(nil),   // 11: mir.v1.StartScenarioRequest
	(*StopScenarioRequest)(nil),    // 12: mir.v1.StopScenarioRequest
	(*Ack)(nil),                    // 13: mir.v1.Ack
	(*PortStats)(nil),              // 14: mir.v1.PortStats
	(*TelemetrySnapshot)(nil),      // 15: mir.v1.TelemetrySnapshot
	(*RxClass)(nil),                // 16: mir.v1.RxClass
	(*Event)(nil),                  // 17: mir.v1.Event
	(*StreamTelemetryRequest)(nil), // 18: mir.v1.StreamTelemetryRequest
	(*StreamEventsRequest)(nil),    // 19: mir.v1.StreamEventsRequest
}
var file_dataplane_proto_depIdxs = []int32{
	3,  // 0: mir.v1.HelloResponse.ports:type_name -> mir.v1.PortInfo
	5,  // 1: mir.v1.PacketSpec.eth:type_name -> mir.v1.EthSpec
	6,  // 2: mir.v1.PacketSpec.ipv4:type_name -> mir.v1.Ipv4Spec
	7,  // 3: mir.v1.PacketSpec.ipv6:type_name -> mir.v1.Ipv6Spec
	8,  // 4: mir.v1.PacketSpec.tcp:type_name -> mir.v1.TcpSpec
	9,  // 5: mir.v1.PacketSpec.udp:type_name -> mir.v1.UdpSpec
	10, // 6: mir.v1.StartScenarioRequest.packet:type_name -> mir.v1.PacketSpec
	14, // 7: mir.v1.TelemetrySnapshot.ports:type_name -> mir.v1.PortStats
	16, // 8: mir.v1.TelemetrySnapshot.rx:type_name -> mir.v1.RxClass
	1,  // 9: mir.v1.Event.kind:type_name -> mir.v1.Event.Kind
	2,  // 10: mir.v1.DataPlane.Hello:input_type -> mir.v1.HelloRequest
	11, // 11: mir.v1.DataPlane.StartScenario:input_type -> mir.v1.StartScenarioRequest
	12, // 12: mir.v1.DataPlane.StopScenario:input_type -> mir.v1.StopScenarioRequest
	18, // 13: mir.v1.DataPlane.StreamTelemetry:input_type -> mir.v1.StreamTelemetryRequest
	19, // 14: mir.v1.DataPlane.StreamEvents:input_type -> mir.v1.StreamEventsRequest
	4,  // 15: mir.v1.DataPlane.Hello:output_type -> mir.v1.HelloResponse
	13, // 16: mir.v1.DataPlane.StartScenario:output_type -> mir.v1.Ack
	13, // 17: mir.v1.DataPlane.StopScenario:output_type -> mir.v1.Ack
	15, // 18: mir.v1.DataPlane.StreamTelemetry:output_type -> mir.v1.TelemetrySnapshot
	17, // 19: mir.v1.DataPlane.StreamEvents:output_type -> mir.v1.Event
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_dataplane_proto_init() }
func file_dataplane_proto_init() {
	if File_dataplane_proto != nil {
		return
	}
	file_dataplane_proto_msgTypes[8].OneofWrappers = []any{
		(*PacketSpec_Ipv4)(nil),
		(*PacketSpec_Ipv6)(nil),
		(*PacketSpec_Tcp)(nil),
		(*PacketSpec_Udp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dataplane_proto_rawDesc), len(file_dataplane_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dataplane_proto_goTypes,
		DependencyIndexes: file_dataplane_proto_depIdxs,
		EnumInfos:         file_dataplane_proto_enumTypes,
		MessageInfos:      file_dataplane_proto_msgTypes,
	}.Build()
	File_dataplane_proto = out.File
	file_dataplane_proto_goTypes = nil
	file_dataplane_proto_depIdxs = nil
}
