// Mir — 데이터플레인 ⇄ 제어부 공용 스키마.
//
// 이 파일 하나가 **두 hop 을 모두 정의**한다.
//
//   ③ C 데이터플레인 ⇄ Go 사이드카   : unix socket + length-prefix framing
//   ④ Go 사이드카   ⇄ Go 제어부      : gRPC (service DataPlane)
//
// 사이드카는 대부분의 필드를 그대로 통과시키는 릴레이라, 스키마를 하나로
// 유지하면 두 hop 이 갈라질 여지가 없다.
//
// ── hop ③ 와이어 포맷 (C 의 ipc_server.c 와 반드시 일치) ──────────────
//
//   +--------+--------+------------------+
//   | u32 be | u16 be |     payload      |
//   | length |  type  |    (protobuf)    |
//   +--------+--------+------------------+
//
//   length = sizeof(type) + sizeof(payload)   — 자기 자신은 제외
//   type   = MsgType 값
//
// gRPC 를 C 에 직접 넣지 않은 이유는 성능이 아니라 **스레드 격리**다.
// C 프로세스에 gRPC 스레드 풀이 생기면 컨테이너 cpuset(= worker 코어 포함)을
// 떠돌며 busy-poll 루프를 선점할 수 있다. 사이드카는 별도 컨테이너라
// 애초에 worker 코어에 올라갈 물리적 경로가 없다.
//
// ── 코드 생성 ─────────────────────────────────────────────────────────
//
//   Go : buf generate            (저장소 루트에서. 생성물은 커밋한다)
//   C  : protoc-c --proto_path=proto --c_out=<builddir> proto/dataplane.proto
//        (meson custom_target 이 빌드 중에 실행 — 이미지 빌드 시점에만 필요)
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: dataplane.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataPlane_Hello_FullMethodName           = "/mir.v1.DataPlane/Hello"
	DataPlane_StartScenario_FullMethodName   = "/mir.v1.DataPlane/StartScenario"
	DataPlane_StopScenario_FullMethodName    = "/mir.v1.DataPlane/StopScenario"
	DataPlane_StreamTelemetry_FullMethodName = "/mir.v1.DataPlane/StreamTelemetry"
	DataPlane_StreamEvents_FullMethodName    = "/mir.v1.DataPlane/StreamEvents"
)

// DataPlaneClient is the client API for DataPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ─────────────────────────────────────────────────────────────
// hop ④ — 사이드카가 서버, 제어부가 클라이언트.
//
// 제어부는 함대 설정(fleet.yaml)에 적힌 주소 집합에 자동으로 연결/해제한다.
// 장비 경계를 넘으므로 이 hop 은 mTLS 로 보호된다 — control/internal/mtls.
// ─────────────────────────────────────────────────────────────
type DataPlaneClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	StartScenario(ctx context.Context, in *StartScenarioRequest, opts ...grpc.CallOption) (*Ack, error)
	StopScenario(ctx context.Context, in *StopScenarioRequest, opts ...grpc.CallOption) (*Ack, error)
	StreamTelemetry(ctx context.Context, in *StreamTelemetryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TelemetrySnapshot], error)
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
}

type dataPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewDataPlaneClient(cc grpc.ClientConnInterface) DataPlaneClient {
	return &dataPlaneClient{cc}
}

func (c *dataPlaneClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, DataPlane_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataPlaneClient) StartScenario(ctx context.Context, in *StartScenarioRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, DataPlane_StartScenario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataPlaneClient) StopScenario(ctx context.Context, in *StopScenarioRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, DataPlane_StopScenario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataPlaneClient) StreamTelemetry(ctx context.Context, in *StreamTelemetryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TelemetrySnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataPlane_ServiceDesc.Streams[0], DataPlane_StreamTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamTelemetryRequest, TelemetrySnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlane_StreamTelemetryClient = grpc.ServerStreamingClient[TelemetrySnapshot]

func (c *dataPlaneClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataPlane_ServiceDesc.Streams[1], DataPlane_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlane_StreamEventsClient = grpc.ServerStreamingClient[Event]

// DataPlaneServer is the server API for DataPlane service.
// All implementations must embed UnimplementedDataPlaneServer
// for forward compatibility.
//
// ─────────────────────────────────────────────────────────────
// hop ④ — 사이드카가 서버, 제어부가 클라이언트.
//
// 제어부는 함대 설정(fleet.yaml)에 적힌 주소 집합에 자동으로 연결/해제한다.
// 장비 경계를 넘으므로 이 hop 은 mTLS 로 보호된다 — control/internal/mtls.
// ─────────────────────────────────────────────────────────────
type DataPlaneServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	StartScenario(context.Context, *StartScenarioRequest) (*Ack, error)
	StopScenario(context.Context, *StopScenarioRequest) (*Ack, error)
	StreamTelemetry(*StreamTelemetryRequest, grpc.ServerStreamingServer[TelemetrySnapshot]) error
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[Event]) error
	mustEmbedUnimplementedDataPlaneServer()
}

// UnimplementedDataPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataPlaneServer struct{}

func (UnimplementedDataPlaneServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedDataPlaneServer) StartScenario(context.Context, *StartScenarioRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method StartScenario not implemented")
}
func (UnimplementedDataPlaneServer) StopScenario(context.Context, *StopScenarioRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method StopScenario not implemented")
}
func (UnimplementedDataPlaneServer) StreamTelemetry(*StreamTelemetryRequest, grpc.ServerStreamingServer[TelemetrySnapshot]) error {
	return status.Error(codes.Unimplemented, "method StreamTelemetry not implemented")
}
func (UnimplementedDataPlaneServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedDataPlaneServer) mustEmbedUnimplementedDataPlaneServer() {}
func (UnimplementedDataPlaneServer) testEmbeddedByValue()                   {}

// UnsafeDataPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataPlaneServer will
// result in compilation errors.
type UnsafeDataPlaneServer interface {
	mustEmbedUnimplementedDataPlaneServer()
}

func RegisterDataPlaneServer(s grpc.ServiceRegistrar, srv DataPlaneServer) {
	// If the following call panics, it indicates UnimplementedDataPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataPlane_ServiceDesc, srv)
}

func _DataPlane_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPlaneServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataPlane_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPlaneServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataPlane_StartScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartScenarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPlaneServer).StartScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataPlane_StartScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPlaneServer).StartScenario(ctx, req.(*StartScenarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataPlane_StopScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopScenarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPlaneServer).StopScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataPlane_StopScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPlaneServer).StopScenario(ctx, req.(*StopScenarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataPlane_StreamTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamTelemetryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataPlaneServer).StreamTelemetry(m, &grpc.GenericServerStream[StreamTelemetryRequest, TelemetrySnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlane_StreamTelemetryServer = grpc.ServerStreamingServer[TelemetrySnapshot]

func _DataPlane_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataPlaneServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlane_StreamEventsServer = grpc.ServerStreamingServer[Event]

// DataPlane_ServiceDesc is the grpc.ServiceDesc for DataPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mir.v1.DataPlane",
	HandlerType: (*DataPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _DataPlane_Hello_Handler,
		},
		{
			MethodName: "StartScenario",
			Handler:    _DataPlane_StartScenario_Handler,
		},
		{
			MethodName: "StopScenario",
			Handler:    _DataPlane_StopScenario_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTelemetry",
			Handler:       _DataPlane_StreamTelemetry_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamEvents",
			Handler:       _DataPlane_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dataplane.proto",
}
